import type { Project } from '@/lib/types'

export const PROJECTS: Project[] = [
  {
    id: 0,
    title: "RealityCheck AI",
    description: "Production-grade deepfake & AI-generated image detection platform — 3-model EfficientNet ensemble cross-validated on DFDC + FaceForensics++, paired with a custom 7-channel forensic artifact engine that catches Stable Diffusion, DALL·E, and Midjourney outputs standard face-swap detectors miss entirely.",
    tech: ["Next.js 15", "React 18", "TypeScript", "Flask", "PyTorch", "OpenCV", "Socket.IO", "Tailwind CSS", "Framer Motion"],
    scope: "Multi-model ensemble inference · 7-channel signal forensics (DCT, noise, edge, JPEG) · BlazeFace GPU-accelerated face detection · Frame-by-frame video analysis · Real-time WebSocket progress · Batch processing · Exportable reports · Zero data persistence (privacy-first)",
    github: "https://github.com/Saqib-Patel/RealityCheck-AI",
    live: "https://realitycheck-ai-two.vercel.app/",
    image: "/previews/realitycheck-ai.png",
  },
  {
    id: 1,
    title: "Streakly",
    description: "Mobile-first habit tracker engineered for consistency — streak logic engine, calendar heatmap, stats dashboard, and category filters backed by Supabase with Row-Level Security ensuring complete user data isolation at the database level. Zero shared state between users by design.",
    tech: ["React 18", "TypeScript", "Vite", "Tailwind CSS", "shadcn/ui", "Framer Motion", "Supabase", "PostgreSQL"],
    scope: "Daily habit tracking · Streak logic engine · Calendar heatmap visualization · Stats & trends dashboard · Category filters · Theme customization · Onboarding flow · Push reminders · Row-Level Security auth",
    github: "https://github.com/Saqib-Patel/streakly",
    live: "https://streakly-dailydrive.vercel.app/",
    image: "/previews/streakly.png",
  },
  {
    id: 2,
    title: "InkBoard",
    description: "Distraction-free infinite canvas whiteboard with pressure-aware freehand strokes via Fabric.js, shape/text annotation tools, laser pointer presentation mode, minimap navigation, and full undo/redo history — engineered for buttery-smooth 60fps interactions on desktop and tablet.",
    tech: ["React 18", "TypeScript", "Vite", "Fabric.js", "Tailwind CSS", "shadcn/ui", "Framer Motion", "React Router"],
    scope: "Infinite pannable/zoomable canvas · Pressure-aware drawing · Shape & text annotation · Laser pointer mode · Minimap navigation · Keyboard shortcuts · Theme customization · Export · Undo/redo stack · Onboarding flow",
    github: "https://github.com/Saqib-Patel/InkBoard",
    live: "https://ink-board.vercel.app/",
    image: "/previews/inkboard.png",
  },
  {
    id: 3,
    title: "Book Inventory System",
    description: "Full-stack inventory management with Goodreads RapidAPI integration for auto-filling book metadata, sortable/paginated data tables, dual grid/table views, and production-grade form validation via Zod + React Hook Form — dark/light theme, fully responsive across all breakpoints.",
    tech: ["React 18", "TypeScript", "Node.js", "Express.js", "MongoDB", "Tailwind CSS", "shadcn/ui"],
    scope: "Complete CRUD operations · Goodreads API auto-fill · Sortable + paginated tables · Grid & table dual views · Real-time Zod validation · Dark/light theme · RESTful Express backend · MongoDB Atlas",
    github: "https://github.com/Saqib-Patel/Book-Inventory",
    live: "https://book-inventory-mu.vercel.app/",
    image: "/previews/book-inventory.png",
  },
]

export const CREDENTIALS = [
  {
    id: 1,
    category: "AWS",
    title: "AWS Certified Solutions Architect – Associate",
    issuer: "Amazon Web Services",
    date: "March 2026",
    tags: ["Cloud", "AWS", "DevOps", "Architecture"],
    description: "Validates expertise in designing scalable, highly available, and fault-tolerant systems on AWS — covering EC2, S3, VPC, IAM, RDS, and core cloud architecture patterns.",
    credentialId: "2a52c550c8b34a8cb290fc012214ccc4",
    verifyUrl: "https://cp.certmetrics.com/amazon/en/public/verify/credential/2a52c550c8b34a8cb290fc012214ccc4",
    color: "#FF9900",
    issuerLogo: "AWS",
    image: "/certs/aws-saa.png",
  },
  {
    id: 2,
    category: "Oracle",
    title: "Oracle Cloud Infrastructure 2024 Certified Foundations Associate",
    issuer: "Oracle University",
    date: "February 28, 2025",
    tags: ["Cloud", "OCI", "Infrastructure", "Oracle"],
    description: "Covers Oracle Cloud Infrastructure core services — security, networking, compute, storage, and foundational cloud concepts for enterprise deployments.",
    credentialId: "101265570OCI2024FNDCFA",
    verifyUrl: "https://drive.google.com/file/d/1ULvtkyzAH4S1Zvh_2jghPY8EL5HLU3Z5/view",
    color: "#F80000",
    issuerLogo: "OCI",
    image: "/certs/oracle-oci.png",
  },
  {
    id: 3,
    category: "GitHub",
    title: "GitHub Foundations",
    issuer: "GitHub",
    date: "January 7, 2025",
    tags: ["Git", "GitHub", "DevOps", "CI/CD", "GitHub Actions"],
    description: "Validates entry-level expertise in GitHub fundamentals — repositories, branching, collaboration workflows, GitHub Actions, and project management.",
    credentialId: "d91f0577-52b7-46d4-9902-f6c7d438fe36",
    verifyUrl: "https://www.credly.com/badges/d91f0577-52b7-46d4-9902-f6c7d438fe36/linked_in_profile",
    color: "#ffffff",
    issuerLogo: "GH",
    image: "/certs/github-foundations.png",
  },
  {
    id: 4,
    category: "PrepInsta",
    title: "MERN Full Stack Web Development",
    issuer: "PrepInsta",
    date: "December 2025",
    tags: ["Full Stack", "MERN", "React", "Node.js", "MongoDB", "Express.js"],
    description: "Covers end-to-end web development using MongoDB, Express.js, React, and Node.js — hands-on project building and REST API integration.",
    credentialId: "692fd8d041cb810a142185aa",
    verifyUrl: "https://drive.google.com/file/d/1KQPwEQsYsjBKpHEGbNXwX-JVymKzHLqg/view?usp=sharing",
    color: "#4285F4",
    issuerLogo: "PI",
    image: "/certs/mern-prepinsta.png",
  },
  {
    id: 5,
    category: "Neo4j",
    title: "Neo4j Certified Professional",
    issuer: "Neo4j",
    date: "June 2025",
    tags: ["Graph Database", "Neo4j", "Cypher", "NoSQL", "Data Engineering"],
    description: "Validates proficiency in graph database concepts, Cypher query language, data modeling, and building applications with Neo4j.",
    credentialId: "3d905522-4ca3-498a-8f11-0c9157fb25e2",
    verifyUrl: "https://graphacademy.neo4j.com/c/3d905522-4ca3-498a-8f11-0c9157fb25e2",
    color: "#00B4D8",
    issuerLogo: "N4J",
    image: "/certs/neo4j-professional.png",
  },
]

export const TECH_STACK = {
  Languages: [
    "C++",
    "Python",
    "C",
    "Java",
    "JavaScript (ES6+)",
    "TypeScript",
    "PHP",
  ],

  Frontend: [
    "React.js",
    "Next.js",
    "Tailwind CSS",
    "Framer Motion",
    "HTML5",
    "CSS3",
  ],

  Backend: [
    "Node.js",
    "Express.js",
    "REST API",
    "Socket.IO",
    "JWT Authentication",
    "Flask",
  ],

  Databases: [
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Firebase",
    "Redis",
  ],

  "ML / AI": [
    "Python",
    "PyTorch",
    "OpenCV",
    "CNN",
    "Pandas",
    "Streamlit",
  ],

  "DevOps & Cloud": [
    "Docker",
    "Linux",
    "CI/CD",
    "GitHub Actions",
    "AWS",
    "Google Cloud Platform",
    "Vercel",
    "Netlify",
  ],

  "Dev Tools": [
    "Git",
    "GitHub",
    "Postman",
    "VS Code",
    "Figma",
    "ESLint",
  ],

  "CS Fundamentals": [
    "Data Structures & Algorithms",
    "OOP",
    "System Design",
    "DBMS",
    "Computer Networks",
    "Agile / Scrum",
  ],
} as const;

export const SOCIAL_LINKS = {
  github: "https://github.com/Saqib-Patel",
  linkedin: "https://linkedin.com/in/mohammedsaqibpatel",
  leetcode: "https://leetcode.com/saqib_patel",
  // kaggle: "https://kaggle.com/saqibpatel",
}